### ISSUE TITLE
Plan of attack Dec 2021 - Jan 2022

### ISSUE THREAD

**Issue by EiffL** [astrodeepnet/sbi_experiments#5]
Following some of our preliminary experiments listed in #2 I think we have a few good ideas and threads to explore, but we should start thinking about concrete milestones and goals in order to be where we want to be by the end of January.  I'm opening this issue to try to track our various todos.

## Goal

By end of January we want to have plots comparing the dependence on number of sampling points of various density estimators to achieve a given accuracy in the modeling of likelihood or posterior distributions. We can push this to various levels:

- **Level 0: Basic requirements**: On a toy model like two moons, or fake weak lensing likelihood toy model, make a plot of number of sims vs accuracy of modeling with existing methods (e.g. various kind of flows).

- **Level 1: Main goal**: Develop a density estimator that can make use of gradient information, add comparison plot to Level 0 plots

- **Level 2: Stretch goal**: Apply the developed density estimator to a realistic WL simulation problem. 

## TODOs

_Method developments_:
- [ ] Implement a C^k with k>2 coupling layer with analytic inverse.
- [ ] Implement a C^k with k>2 coupling layer with numerical inverse and implicit function theorem.
- [ ] Verify the smoothness of ODE Flows and try to train with gradient constraints 

_Simulation developments_:
- [ ] Add code needed for basic test distributions in a differentiable way (e.g two moons, roll)
- [ ] Implement a simple WL toy likelihood model (e.g. fitting gaussian mixture to actual WL likelihood)
- [ ] Implement simple WL field level simulator (e.g. based on https://github.com/tlmakinen/kosmo-kompress )

_Comparison infrastructure_:
- [ ] Decide on metrics to compare performance of NDEs
- [ ] Add scripts to make plots comparing different NDEs on different distributions
